### ISSUE TITLE
VAPID config not found in bundle config resulting in endpoint reporting 401 missing auth headers

### ISSUE THREAD

**Issue by veldenb** [Minishlink/web-push-bundle#19]
https://github.com/Minishlink/web-push-bundle/blob/e6d2dd8496d2f41e1e86f4e299f50eb5dad788f2/DependencyInjection/MinishlinkWebPushExtension.php#L31

I'm not sure but the last bundle update to version 6 seems to break the VAPID-config.
Currently the auth array seems to miss the VAPID-key. Adding the key fixes the missing config for me:
```
$container->setParameter('minishlink_web_push.auth', isset($config['VAPID']) ? ['VAPID' => $config['VAPID']] : []);
```

**Comment by stephanvierkant** [comment]
Yes, that fixes https://github.com/web-push-libs/web-push-php/issues/293 for me. Thanks! I'll create a PR.
