### ISSUE TITLE
Create a branch for minishlink/web-push:2.0

### ISSUE THREAD

**Issue by vjnrv** [Minishlink/web-push-bundle#8]
Hello, thanks for your bundle.

Could you create a branch to minishlink/web-push:2.0? It seens that i need to run that version to be compatible with PHP 7.2.

Thanks

**Comment by rodrigm** [comment]
Same problem, any news?

Thanks!

**Comment by Minishlink** [comment]
Hello, this is available on https://github.com/Minishlink/web-push-bundle/releases/tag/v2.0.0 :)

**Comment by rodrigm** [comment]
Thanks! 🎉
