### ISSUE TITLE
Outdated dependency

### ISSUE THREAD

**Issue by GenieTim** [Minishlink/web-push-bundle#9]
Thank you for this bundle. I have a question regarding its actuality; when running `composer outdated`, it lists the dependency `minishlink/web-push v2.0.1` as outdated. The current version is `~ v4.0.2`. Is there a specific reason for beeing outdated? If not, is someone working or should I open a PR for an upgrade?

Best regards

**Comment by Minishlink** [comment]
Thanks @BernhardWebstudio, I don't have the need nor the time right now to update the web-push dependency, so I'll be glad to review a PR of yours, thanks!
The different version changelog should be straightforward [here](https://github.com/web-push-libs/web-push-php/releases).

**Comment by Minishlink** [comment]
Available in v3.0.0 😃
